### ISSUE TITLE
Provide a library function/method for converting a glob to an uncompiled regex string.

### ISSUE THREAD

**Issue by kwlzn** [cpburnz/python-path-specification#11]
currently, the way to get a regex string for a given gitignore-style glob is:

```
>>> pathspec.GitIgnorePattern('/dist/').regex.pattern
'^dist/.*$'
```

which incurs the glob->regex translation inside `GitIgnorePattern.__init__` which in turn calls `RegexPattern.__init__` which automatically compiles the regex.

for the simple case of just wanting to convert a glob into a non-compiled regex string, it'd be great to have a utility function/method that could both be used inside `GitIgnorePattern.__init__` and outside as part of the public API.

**Comment by cpburnz** [comment]
I could make a class method part of `RegexPattern` to convert the glob patterns to the regular expression strings.

```python
@classmethod
def pattern_to_regex(cls, pattern) -> (regex, include)
```

`GitIgnorePattern` would then implement it and use it inside of its `__init__()`. If you want access to the raw regex string, you could acquire it via:

```python
>>> pathspec.GitIgnorePattern.pattern_to_regex('/dist/')
('^dist/.*$', True)
```

**Comment by kwlzn** [comment]
sgtm!

**Comment by cpburnz** [comment]
@kwlzn This has been implemented.

**Comment by kwlzn** [comment]
@cpburnz awesome, thank you!
