### ISSUE TITLE
Python 2.6 support

### ISSUE THREAD

**Issue by adrienverge** [cpburnz/python-path-specification#16]
Hi,

Since today, pathspec is used by yamllint, which is used by Ansible, OpenStack and others.

The problem is: all these software must support Python 2.6, but pathspec currently doesn't. This leads to issues like https://github.com/adrienverge/yamllint/issues/55 and https://github.com/ansible/ansible/pull/26186.

In your opinion, what's the amount of work needed to support Python 2.6?

**Comment by cpburnz** [comment]
As much as I think everyone should be migrating to Python 3, supporting Python 2.6 would be trivial. It looks like there's that set-comprehension and a utility method that needs a slight tweak. So very little work is needed.

**Comment by cpburnz** [comment]
@adrienverge Python 2.6 support has been added. I tested it through *tox* and everything seems to be in order.

**Comment by adrienverge** [comment]
@cpburnz thanks a lot!
