### ISSUE TITLE
a "./" infront of the filename provides wrong matches

### ISSUE THREAD

**Issue by spMohanty** [cpburnz/python-path-specification#20]
Consider the use case when you have a directory structure like this : 
```
.
|-- 0.csv
|-- A
|   `-- 1.csv
`-- .gitignore
```

and the contents of `.gitignore` are : 
```
*.csv
!A/0.csv
```

`ignorespec.match_file("A/0.csv")` returns `True`, which is expected. 
while 
`ignorespec.match_file("./A/0.csv")` returns `False`.

**Comment by cpburnz** [comment]
@spMohanty Thank you for the two reports. I'll look into them this week.

**Comment by cpburnz** [comment]
@spMohanty This is now supported.
