### ISSUE TITLE
Deprecation warining

### ISSUE THREAD

**Issue by thmxv** [cpburnz/python-path-specification#21]
I get the following deprecation warning

/usr/lib/python3.7/site-packages/pathspec/pathspec.py:27: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  self.patterns = patterns if isinstance(patterns, collections.Container) else list(patterns)

**Comment by cpburnz** [comment]
This is now fixed. It will use `collections.abc` where it's available (Python 3.3+), and fallback to `collections` for 2.6-3.2.
