### ISSUE TITLE
method to escape gitwildmatch

### ISSUE THREAD

**Issue by mroutis** [cpburnz/python-path-specification#26]
It would be great to have a method for escaping a string according to gitwildmatch, thus, putting backslashes before `!`, `[`, `]`, `?` `*`.

I could send a PR if there's interest on this

**Comment by cpburnz** [comment]
@mroutis That would be a useful addition. I'm interested in a PR.

**Comment by mroutis** [comment]
Cool, @cpburnz !  I'll be submitting a patch for it (a very basic one, but at least to start the conversation)
