### ISSUE TITLE
Feature request: Accept Path as arguments

### ISSUE THREAD

**Issue by pykong** [cpburnz/python-path-specification#33]
We write the year 2020: Pythonistas have largely adopted the use of the `pathlib` module as a more convenient way to perform file system operation that old stinkin `os.path` and its comrades.

Hence it would be great if all of `pathspec` function would accept Path objects or iterables thereof as arguments, compared to plain strings.

Putting a conversion to a string via `str(my_path)` at the right places is all it takes to make it work.

**Comment by cpburnz** [comment]
@pykong That would be a useful addition. I'll review your pull request.
