### ISSUE TITLE
Support Python Pathlib

### ISSUE THREAD

**Issue by logavanc** [cpburnz/python-path-specification#37]
The `match_file` and `match_files` functions do not seem to support `pathlib.Path` objects, which would be convenient.  If that is something that you want, I would be happy to work on a pull request.

**Comment by cpburnz** [comment]
@logavanc Support was added by #34. I have not published a new release yet because I want to address a couple of the other open issues first.

**Comment by cpburnz** [comment]
v0.8.0 has been released.
