### ISSUE TITLE
Missing version git tags

### ISSUE THREAD

**Issue by kloczek** [cpburnz/python-path-specification#42]
Accorging to https://pypi.org/project/pathspec/ latest version is 0.8.0 but there is no any version git tags here.

**Comment by cpburnz** [comment]
Up until now I've published new packages on PyPI and titled the commits as "Release v{x}.{y}.{z}". I haven't published any packages on Github.

**Comment by kloczek** [comment]
I've not been asking to publish anything but just **tag** git repo to be albe to see that has been commited **after** exact release :)

**Comment by kloczek** [comment]
Still no version git tags :(

**Comment by ftrofin** [comment]
I second this request. It's quite easy to create a Release from github.

**Comment by cpburnz** [comment]
The latest release, [v0.8.1](https://github.com/cpburnz/python-path-specification/releases/tag/v0.8.1), is now tagged.
