### ISSUE TITLE
IndexError: list index out of range in pattern_to_regex

### ISSUE THREAD

**Issue by sanderland** [cpburnz/python-path-specification#44]
I encountered an exeption in pathspec when
This line gives an error when the string "!\n" is passed, specifically due to a stray linebreak in the .gitignore file.
https://github.com/cpburnz/python-path-specification/blob/master/pathspec/patterns/gitwildmatch.py#L112

I am not sure what the expected behaviour is here, but it may be best to ignore rather than crash on the line.

**Comment by caleb-partsgiant** [comment]
Hi @sanderland, I can't reproduce this error. Based upon the line you referenced, if there's a bug this should trigger it:

```python
>>> from pathspec.patterns.gitwildmatch import GitWildMatchPattern
>>> GitWildMatchPattern.pattern_to_regex("!'n")
("^(?:.+/)?\\'n$", False)
>>> GitWildMatchPattern.pattern_to_regex("!'n\n")
("^(?:.+/)?\\'n$", False)
```

Can you provide a minimal example replicating the error you encountered?

**Comment by cpburnz** [comment]
Hi @sanderland, I can't reproduce this error. Based upon the line you referenced, if there's a bug this should trigger it:

```python
>>> from pathspec.patterns.gitwildmatch import GitWildMatchPattern
>>> GitWildMatchPattern.pattern_to_regex("!'n")
("^(?:.+/)?\\'n$", False)
>>> GitWildMatchPattern.pattern_to_regex("!'n\n")
("^(?:.+/)?\\'n$", False)
```


Can you provide a minimal example replicating the error you encountered?

**Comment by sanderland** [comment]
Sorry the `' ` was stray, the bug was triggered by a single line containing ONLY `!`

**Comment by cpburnz** [comment]
Thank you. That reproduces the error:

```python
>>> GitWildMatchPattern.pattern_to_regex("!")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.../python-path-specification/pathspec/patterns/gitwildmatch.py", line 112, in pattern_to_regex
    if not pattern_segs[-1] and len(pattern_segs) > 1:
IndexError: list index out of range
```
