### ISSUE TITLE
Create github releases/git tags for versions

### ISSUE THREAD

**Issue by saltedcoffii** [cpburnz/python-path-specification#49]
Commit 7b125acf41702cb82679dcf56aaf6a14d34bd785 can be tagged with 0.8.1 for example.

This would be helpful for non-pip package managers such as chromebrew, which I'm packaging pathspec for right now.

**Comment by cpburnz** [comment]
I've now tagged the [v0.8.1](https://github.com/cpburnz/python-path-specification/releases/tag/v0.8.1) commit.
